export const allTextureKeys = {
	attackExplosion: 'attackExplosion',
	attackExplosionJSON: 'attackExplosionJSON',
	backgroundWide: 'backgroundWide',
	battleButton: 'battleButton',
	buttonYellow: 'button_yellow',
	buttonYellowPlusText: 'button_yellow_plus_text',
	cardCommonFrame: 'CardCommonFrame',
	cardCommonFull: 'CardCommonFull',
	cardLegendaryFrame: 'CardLegendaryFrame',
	cardLegendaryFull: 'CardLegendaryFull',
	cardMask: 'CardMask',
	cardMaskShine: 'CardMaskShine',
	circleCyan: 'circleCyan',
	circleViolet: 'circleViolet',
	enemiesIcon: 'enemies_icon',
	field: 'field',
	gunslinger1Attack: 'gunslinger1_attack',
	gunslinger1Idle: 'gunslinger1_idle',
	gunslinger1Move: 'gunslinger1_move',
	gunslinger2Attack: 'gunslinger2_attack',
	gunslinger2Idle: 'gunslinger2_idle',
	gunslinger2Move: 'gunslinger2_move',
	gunslinger3Attack: 'gunslinger3_attack',
	gunslinger3Idle: 'gunslinger3_idle',
	gunslinger3Move: 'gunslinger3_move',
	hand: 'hand',
	hpBarEmpty: 'hpBar_empty',
	hpBarEnemy: 'hpBar_enemy',
	hpBarHero: 'hpBar_hero',
	hpBarMask: 'hpBar_mask',
	levelOneEnemy: 'level_one_enemy',
	levelOneHero: 'level_one_hero',
	levelThreeEnemy: 'level_three_enemy',
	levelThreeHero: 'level_three_hero',
	levelTwoHero: 'level_two_hero',
	logo: 'logo',
	mergeExplosion: 'mergeExplosion',
	mergeExplosionJSON: 'mergeExplosionJSON',
	minotaur1Attack: 'minotaur1_attack',
	minotaur1Idle: 'minotaur1_idle',
	minotaur1Move: 'minotaur1_move',
	minotaur2Attack: 'minotaur2_attack',
	minotaur2Idle: 'minotaur2_idle',
	minotaur2Move: 'minotaur2_move',
	minotaur3Attack: 'minotaur3_attack',
	minotaur3Idle: 'minotaur3_idle',
	minotaur3Move: 'minotaur3_move',
	playNowButton: 'play_now_button',
	playNowButton2: 'play_now_button2',
	rewardChestClosed: 'rewardChest_closed',
	rewardChestOpened: 'rewardChest_opened',
	shine2: 'shine2',
	shine3: 'shine3',
	skeletonAttack: 'skeleton_attack',
	skeletonIdle: 'skeleton_idle',
	skeletonKingAttack: 'skeletonKing_attack',
	skeletonKingIdle: 'skeletonKing_idle',
	skeletonMove: 'skeleton_move',
	soundOff: 'soundOff',
	soundOn: 'soundOn',
	threeGradeEnemy: 'three_grade_enemy'
};

export const appTextures = {
	[allTextureKeys.attackExplosion]: 'img/attackExplosion.webp',
	[allTextureKeys.backgroundWide]: 'img/backgroundWide.avif',
	[allTextureKeys.battleButton]: 'img/battleButton.webp',
	[allTextureKeys.buttonYellow]: 'img/button_yellow.webp',
	[allTextureKeys.buttonYellowPlusText]: 'img/button_yellow_plus_text.webp',
	[allTextureKeys.cardCommonFrame]: 'img/CardCommonFrame.webp',
	[allTextureKeys.cardCommonFull]: 'img/CardCommonFull.webp',
	[allTextureKeys.cardLegendaryFrame]: 'img/CardLegendaryFrame.webp',
	[allTextureKeys.cardLegendaryFull]: 'img/CardLegendaryFull.webp',
	[allTextureKeys.cardMask]: 'img/CardMask.webp',
	[allTextureKeys.cardMaskShine]: 'img/CardMaskShine.webp',
	[allTextureKeys.circleCyan]: 'img/circleCyan.webp',
	[allTextureKeys.circleViolet]: 'img/circleViolet.webp',
	[allTextureKeys.enemiesIcon]: 'img/enemies_icon.webp',
	[allTextureKeys.field]: 'img/field.webp',
	[allTextureKeys.hand]: 'img/hand.webp',
	[allTextureKeys.hpBarEmpty]: 'img/hpBar_empty.webp',
	[allTextureKeys.hpBarEnemy]: 'img/hpBar_enemy.webp',
	[allTextureKeys.hpBarHero]: 'img/hpBar_hero.webp',
	[allTextureKeys.hpBarMask]: 'img/hpBar_mask.webp',
	[allTextureKeys.levelOneEnemy]: 'img/level_one_enemy.webp',
	[allTextureKeys.levelOneHero]: 'img/level_one_hero.webp',
	[allTextureKeys.levelThreeEnemy]: 'img/level_three_enemy.webp',
	[allTextureKeys.levelThreeHero]: 'img/level_three_hero.webp',
	[allTextureKeys.levelTwoHero]: 'img/level_two_hero.webp',
	[allTextureKeys.logo]: 'img/logo.webp',
	[allTextureKeys.mergeExplosion]: 'img/mergeExplosion.webp',
	[allTextureKeys.playNowButton]: 'img/play_now_button.webp',
	[allTextureKeys.playNowButton2]: 'img/play_now_button2.webp',
	[allTextureKeys.rewardChestClosed]: 'img/rewardChest_closed.webp',
	[allTextureKeys.rewardChestOpened]: 'img/rewardChest_opened.webp',
	[allTextureKeys.shine2]: 'img/shine2.webp',
	[allTextureKeys.shine3]: 'img/shine3.webp',
	[allTextureKeys.soundOff]: 'img/soundOff.webp',
	[allTextureKeys.soundOn]: 'img/soundOn.webp',
	[allTextureKeys.threeGradeEnemy]: 'img/three_grade_enemy.webp',
	
	[allTextureKeys.attackExplosionJSON]: 'img/attackExplosion.json',
	[allTextureKeys.mergeExplosionJSON]: 'img/mergeExplosion.json',
	
	// Gunslinger анимации
	[allTextureKeys.gunslinger1Attack]: 'img/gunslinger1_attack.json',
	[allTextureKeys.gunslinger1Idle]: 'img/gunslinger1_idle.json',
	[allTextureKeys.gunslinger1Move]: 'img/gunslinger1_move.json',
	[allTextureKeys.gunslinger2Attack]: 'img/gunslinger2_attack.json',
	[allTextureKeys.gunslinger2Idle]: 'img/gunslinger2_idle.json',
	[allTextureKeys.gunslinger2Move]: 'img/gunslinger2_move.json',
	[allTextureKeys.gunslinger3Attack]: 'img/gunslinger3_attack.json',
	[allTextureKeys.gunslinger3Idle]: 'img/gunslinger3_idle.json',
	[allTextureKeys.gunslinger3Move]: 'img/gunslinger3_move.json',
	
	// Minotaur анимации
	[allTextureKeys.minotaur1Attack]: 'img/minotaur1_attack.json',
	[allTextureKeys.minotaur1Idle]: 'img/minotaur1_idle.json',
	[allTextureKeys.minotaur1Move]: 'img/minotaur1_move.json',
	[allTextureKeys.minotaur2Attack]: 'img/minotaur2_attack.json',
	[allTextureKeys.minotaur2Idle]: 'img/minotaur2_idle.json',
	[allTextureKeys.minotaur2Move]: 'img/minotaur2_move.json',
	[allTextureKeys.minotaur3Attack]: 'img/minotaur3_attack.json',
	[allTextureKeys.minotaur3Idle]: 'img/minotaur3_idle.json',
	[allTextureKeys.minotaur3Move]: 'img/minotaur3_move.json',
	
	// Skeleton анимации
	[allTextureKeys.skeletonAttack]: 'img/skeleton_attack.json',
	[allTextureKeys.skeletonIdle]: 'img/skeleton_idle.json',
	[allTextureKeys.skeletonMove]: 'img/skeleton_move.json',
	[allTextureKeys.skeletonKingAttack]: 'img/skeletonKing_attack.json',
	[allTextureKeys.skeletonKingIdle]: 'img/skeletonKing_idle.json'
};

export const audioAssets = {
	hit: 'audio/hit.mp3',
	merge: 'audio/merge.mp3',
	music: 'audio/music.mp3',
	shot: 'audio/shot.mp3',
	splash: 'audio/splash.mp3'
};
