export const labels = {
	game: 'game',
	sound: 'sound',
	muteSlash: 'muteSlash',
	finger: 'finger',
	sceneFinish: 'sceneFinish',
	scene: 'scene',
	sceneBg: 'sceneBg',
	button: 'button',
	buttonTop: 'buttonTop',
	background: 'background',
	logo: 'logo',
	textButton: 'textButton',
	playButton: 'playButton',
	buttonRetry: 'buttonRetry',
	battleButton: 'battleButton',
	
	// Characters
	hero: 'hero',
	heroContainer: 'heroContainer',
	enemy: 'enemy',
	enemyContainer: 'enemyContainer',
	skeleton: 'skeleton',
	skeletonKing: 'skeletonKing',
	gunslinger1: 'gunslinger1',
	gunslinger2: 'gunslinger2',
	gunslinger3: 'gunslinger3',
	minotaur1: 'minotaur1',
	minotaur2: 'minotaur2',
	minotaur3: 'minotaur3',
	shadowMerge: 'shadowMerge',
	heroOne: 'heroOne',
	heroTwo: 'heroTwo',
	heroAttack: 'heroAttack',
	heroMove: 'heroMove',
	explosion: 'explosion',
	
	// UI Components
	hpBar: 'hpBar',
	hpBarEnemy: 'hpBarEnemy',
	
	gameOver: 'gameOver',
	gameWin: 'gameWin',
	gameStart: 'gameStart',
	levelOne: 'levelOne',
	levelTwo: 'levelTwo',
	levelThree: 'levelThree',
	finishLost: 'finishLost',
	finishWin: 'finishWin',
};

export const elementType = {
	SPRITE: 'sprite',
	CONTAINER: 'container',
	TEXT: 'text',
	GRAPHICS: 'graphics',
	ANIMATED_SPRITE: 'animation',
};
